spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc.batch_size: 100
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

reward:
  id: "reward"
  subject: "매일 00 시 00 분 00 초 선착순 10 명 100 포인트 지급!!!"
  description: "• 보상 지급 방식은 사용자가 받기를 누를 때 지급 하게됩니다.
  • 선착순 10 명에게 100 포인트의 보상이 지급되며 10 명 이후에는 지급되지 않아야 합니다.
  • 3 일 연속, 5 일 연속, 10 일 연속 보상을 받는경우 300 포인트, 500 포인트, 1,000 포인트를 추가 보상 받게 됩니다.
  • 추가 보상은 10 일 까지 이어지며 그 이후 연속보상 횟수는 1 회 부터 다시 시작 됩니다"
